---
- name: Cassandra | Add datastax APT repository keys
  apt_key: url=http://debian.datastax.com/debian/repo_key state=present

- name: Cassandra | Add datastax APT repository
  apt_repository: repo="deb http://debian.datastax.com/community stable main" state=present

- name: Cassandra | Stop Cassandra from running with default config
  template: src=policy-rc.d.j2 dest=/usr/sbin/policy-rc.d mode=0755

- name: Cassandra | Install package
  apt: name={{ item }} state=present update-cache=yes force=yes
  with_items:
    - "{{ cassandra_dsc_version }}={{ cassandra_version }}-1"
    - "cassandra={{ cassandra_version }}"

- name: Cassandra | Setup configuration file
  template: src=cassandra.yaml dest={{ cassandra_configuration_dir }}/cassandra.yaml

- name: Cassandra | Copy Cassandra env
  template: src=cassandra-env.sh.j2 dest={{ cassandra_configuration_dir }}/cassandra-env.sh

- name: Cassandra | Remove policy-rc.d file so Cassandra can start
  file: path=/usr/sbin/policy-rc.d state=absent
  notify:
    - restart cassandra
